from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.units import inch
from reportlab.lib import colors
import barcode
from barcode.writer import ImageWriter
import io
import os
from typing import Optional

class PDFEngine:
    @staticmethod
    def generate_receipt(
        school_name: str, 
        student_name: str, 
        custom_id: str, 
        amount: float, 
        slip_number: str, 
        logo_path: Optional[str] = None
    ):
        """
        Generates a PDF receipt with a watermarked logo.
        """
        buffer = io.BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Draw Watermark (15% opacity)
        if logo_path and os.path.exists(logo_path):
            p.saveState()
            p.setFillAlpha(0.15)
            # Center the logo
            logo_width = 4 * inch
            logo_height = 4 * inch
            p.drawImage(logo_path, (width - logo_width) / 2, (height - logo_height) / 2, width=logo_width, height=logo_height, mask='auto')
            p.restoreState()

        # Header
        p.setFont("Helvetica-Bold", 16)
        p.drawCentredString(width / 2, height - 1 * inch, school_name)
        p.setFont("Helvetica", 12)
        p.drawCentredString(width / 2, height - 1.25 * inch, "OFFICIAL PAYMENT RECEIPT")
        
        p.line(1 * inch, height - 1.5 * inch, width - 1 * inch, height - 1.5 * inch)

        # Body
        p.setFont("Helvetica-Bold", 12)
        p.drawString(1 * inch, height - 2 * inch, f"Student Name: {student_name}")
        p.drawString(1 * inch, height - 2.25 * inch, f"Student ID: {custom_id}")
        p.drawString(1 * inch, height - 2.5 * inch, f"Slip Number: {slip_number}")
        
        p.setFont("Helvetica-Bold", 14)
        p.drawString(1 * inch, height - 3 * inch, f"Amount Paid: ${amount:,.2f}")
        
        # Footer
        p.setFont("Helvetica-Oblique", 10)
        p.drawCentredString(width / 2, 1 * inch, "Generated by CRAFT SMS - Unified Educational Platform")
        
        p.showPage()
        p.save()
        
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_eid_card(
        school_name: str, 
        student_name: str, 
        custom_id: str, 
        avatar_path: Optional[str] = None
    ):
        """
        Generates a digital ID card with a barcode.
        """
        buffer = io.BytesIO()
        # Card size: 3.375 x 2.125 inches (Standard ID card)
        card_width = 3.375 * inch
        card_height = 2.125 * inch
        
        p = canvas.Canvas(buffer, pagesize=(card_width, card_height))

        # Background color
        p.setFillColor(colors.HexColor("#f3f4f6"))
        p.rect(0, 0, card_width, card_height, fill=1)

        # Header
        p.setFillColor(colors.HexColor("#0D9488"))
        p.rect(0, card_height - 0.5 * inch, card_width, 0.5 * inch, fill=1)
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 8)
        p.drawCentredString(card_width / 2, card_height - 0.3 * inch, school_name)

        # Photo Placeholder
        p.setFillColor(colors.lightgrey)
        p.rect(0.2 * inch, 0.6 * inch, 0.8 * inch, 0.8 * inch, fill=1)
        if avatar_path and os.path.exists(avatar_path):
             p.drawImage(avatar_path, 0.2 * inch, 0.6 * inch, width=0.8 * inch, height=0.8 * inch)
        
        # Details
        p.setFillColor(colors.black)
        p.setFont("Helvetica-Bold", 9)
        p.drawString(1.1 * inch, 1.2 * inch, student_name)
        p.setFont("Helvetica", 7)
        p.drawString(1.1 * inch, 1.0 * inch, f"ID: {custom_id}")
        p.drawString(1.1 * inch, 0.8 * inch, "Role: STUDENT")

        # Barcode
        EAN = barcode.get_barcode_class('code128')
        # We use custom_id for barcode, but we need to remove underscores if they cause issues
        # code128 supports underscores
        barcode_buffer = io.BytesIO()
        ean = EAN(custom_id, writer=ImageWriter())
        ean.write(barcode_buffer)
        
        barcode_buffer.seek(0)
        p.drawImage(barcode_buffer, 0.2 * inch, 0.1 * inch, width=3 * inch, height=0.4 * inch)

        p.showPage()
        p.save()
        
        buffer.seek(0)
        return buffer
